# Generated by Django 5.0.4 on 2024-06-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_paymentdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='TotalPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
